// <auto-generated />
using CalculadoraCientifica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculadoraCientifica.Migrations
{
    [DbContext(typeof(CalculadoraContext))]
    [Migration("20230522071401_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CalculadoraCientifica.Models.Calculadora", b =>
                {
                    b.Property<int>("CalcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalcId"), 1L, 1);

                    b.Property<string>("Operacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Operador")
                        .HasColumnType("float");

                    b.Property<double>("Resultado")
                        .HasColumnType("float");

                    b.HasKey("CalcId");

                    b.ToTable("Calculos");
                });
#pragma warning restore 612, 618
        }
    }
}
